# -*- coding: utf-8 -*-
"""py project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11YoA9ip8CU-raN5fQb26K0h1YR7a_pWq
"""

# Mood-Based Productivity Recommender

import datetime
import random

# Mood database
mood_actions = {
    "happy": {
        "suggestion": ["Do creative work", "Plan tomorrow", "Learn something new"],
        "music": ["Lo-fi beats", "Soft acoustic"],
        "focus": 9
    },
    "sad": {
        "suggestion": ["Take a walk", "Listen to uplifting music", "Write your feelings down"],
        "music": ["Motivational songs", "Light piano"],
        "focus": 4
    },
    "tired": {
        "suggestion": ["Take a nap", "Drink water", "Do stretching"],
        "music": ["Calm nature sounds", "Slow jazz"],
        "focus": 3
    },
    "stressed": {
        "suggestion": ["Meditate for 5 mins", "Watch something funny", "Talk to a friend"],
        "music": ["Meditation music", "Relaxing sounds"],
        "focus": 2
    },
    "excited": {
        "suggestion": ["Start a new project", "Do brainstorming", "Workout"],
        "music": ["Energetic beats", "Pop music"],
        "focus": 8
    },
    "neutral": {
        "suggestion": ["Review goals", "Organize workspace", "Read a short article"],
        "music": ["Lo-fi or soft rock"],
        "focus": 6
    }
}

mood_log = []

def get_recommendation():
    mood = input("Enter your current mood (Happy, Sad, Tired, Stressed, Excited, Neutral): ").lower()
    if mood not in mood_actions:
        print("❌ Mood not recognized. Try again.\n")
        return

    mood_data = mood_actions[mood]
    suggestion = random.choice(mood_data["suggestion"])
    music = random.choice(mood_data["music"])
    focus = mood_data["focus"]
    date = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    print("\n✨ Mood Report ✨")
    print(f"🕒 Time: {date}")
    print(f"😊 Mood: {mood.capitalize()}")
    print(f"💡 Suggested Activity: {suggestion}")
    print(f"🎵 Music Type: {music}")
    print(f"🔥 Focus Index: {focus}/10\n")

    mood_log.append({"date": date, "mood": mood, "activity": suggestion, "focus": focus})

def show_history():
    if not mood_log:
        print("No mood data recorded yet.\n")
        return
    print("\n------ Mood History ------")
    for m in mood_log:
        print(f"{m['date']} - {m['mood'].capitalize()} - {m['activity']} (Focus: {m['focus']})")
    print("--------------------------\n")

def save_data():
    with open("mood_history.txt", "w") as f:
        for m in mood_log:
            f.write(f"{m['date']},{m['mood']},{m['activity']},{m['focus']}\n")
    print("📁 Data saved to 'mood_history.txt'\n")

def main():
    print("======= Mood-Based Productivity Recommender =======")
    while True:
        print("1️⃣ Get Recommendation")
        print("2️⃣ View Mood History")
        print("3️⃣ Save & Exit")
        choice = input("Choose an option (1-3): ")

        if choice == "1":
            get_recommendation()
        elif choice == "2":
            show_history()
        elif choice == "3":
            save_data()
            print("👋 Goodbye! Take care of your mood ❤️")
            break
        else:
            print("❌ Invalid choice. Try again.\n")

if __name__ == "__main__":
    main()

